Repository cyberark/cloudfoundry-conjur-buildpack, pull requests merged in 2018-02, with the labels that each got.

#12 buildpack has summon version pinned
  lib/0000_install-summon.sh
Labels: in progress, review

#10 CONJ-4695 - Buildpack is updated to pull in Conjur version / ssl cert
  ci/features/step_definitions/common_steps.rb
  lib/0001_retrieve-secrets.sh
  setup-conjur.sh
Labels: review

#13 Buildpack causes error when credentials include Fixnum
  lib/0001_retrieve-secrets.sh
Labels: bug, in progress, review

#14 Updating VERSION to 0.2.1 for v4 support
  CHANGELOG.md
Labels: review

#15 Updating VERSION file
  VERSION
Labels: in progress, review

#16 Revising version to 0.3.0
  CHANGELOG.md
  VERSION
Labels: in progress, review
